runtime: python
env: flex
entrypoint: gunicorn -b :8080 main:app

service: code-test-flask

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10